name: Build MPD

on:
  workflow_dispatch:
  schedule:
  - cron: "0 * * * *"

jobs:
  start_building_gmscore:
    runs-on: ubuntu-22.04
    permissions: write-all
    steps:
    - uses: actions/checkout@v3

    - name: Prepare environment
      run: |
        sudo sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list

    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Gradle
      uses: burrunan/gradle-cache-action@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          meson \
          ccache \
          quilt

    - id: cache-ccache
      uses: hendrikmuhs/ccache-action@v1
      with:
        key: android

    - name: Get next version code
      id: next_ver_code
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        TAG=$(gh release list -L 1 | awk -F '\t' '{print $3}')
        if [ -z "$TAG" ]; then TAG=0; fi
        echo "NEXT_VER_CODE=$((TAG + 1))" >> $GITHUB_OUTPUT

    - name: Execute build script
      run: bash ./build.sh
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: $GITHUB_REPOSITORY
          NEXT_VER_CODE: ${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}

    - name: UPLOAD MPD
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./prebuilt/*
        tag: ${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}
        overwrite: true
        body: "MPD RELEASE"
        file_glob: true
